version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/:/app/
    ports:
      - "80:80"

  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./app/:/usr/share/nginx/html/
  #   ports:
  #     - "80:80"

  # router:
  #   build:
  #     context: ./router
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   restart: unless-stopped      
