version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/:/app/
    ports:
      - "3050:3050"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/:/usr/share/nginx/html/
    ports:
      - "80:80"
