FROM alpine

#Install build tools
RUN apk add alpine-sdk

#Install python
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

#Install packages
RUN apk add python3-dev
RUN pip3 install -U pip
RUN pip3 install wheel
RUN pip3 install uvicorn
RUN pip3 install uvloop
RUN pip3 install gunicorn
RUN pip3 install requests
RUN pip3 install aiofiles
RUN pip3 install jinja2
RUN pip3 install fastapi
RUN pip3 install redis
RUN pip3 install sqlalchemy
RUN pip3 install pymysql
RUN pip3 install pytest
RUN pip3 install pyyaml

#Workdir and files
WORKDIR /app/
COPY ./ ./

#Start server
CMD ["uvicorn", "--reload", "--host", "0.0.0.0", "--port", "80", "main:app"]